[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
voca-core = { workspace = true }
voca-fetcher = { workspace = true }
voca-storage = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
